openapi: '3.0.3'
info:
  title: Judge to Backend API
  version: '0.1'
  license:
    name: MIT
    url: 'https://github.com/traP-jp/traO-Judge-docs/blob/main/LICENSE'
servers:
  - url: https://api.server.test/v1
paths:
  '/judge':
    post:
      description: 全てのジャッジ
      tags:
        - judge
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Judge'
        required: true
      summary: 全てのジャッジ
      responses:
        '200':
          description: OK
components:
  schemas:
    FileAccessibility:
      title: FileAccessibility
      type: string
      description: ファイルのアクセス権限
      enum:
        - invisible
        - readonly
        - readwrite
    ResourceDeclaration:
      title: ResourceDeclaration
      type: object
      description: 必要なリソースの宣言
      properties:
        directoryCount:
          title: directoryCount
          type: number
          description: ディレクトリの数
          example: 3
        textResourceCount:
          title: textResourceCount
          type: number
          description: テキストリソースの数
          example: 3
        oneTimeTextCount:
          title: oneTimeTextCount
          type: number
          description: テキストデータの数
          example: 3
    ResourceDefinition:
      title: ResourceDefinition
      type: object
      description: 必要なリソースの定義
      properties:
        textResourceIds:
          title: textResourceIds
          type: array
          description: 変化しないテキストリソースのID
          items:
            type: string
            format: uuid
            example: 68ffddc4-adc6-4f93-9ff2-d862ee6cce7a
        oneTimeTexts:
          title: oneTimeTexts
          type: array
          description: 動的に変化するテキストデータ
          items:
            type: string
            example: |
              user-1: 100
              user-2: 200
    ResourceAccessibilities:
      title: ExecResourceAccessibilities
      type: object
      description: リソースのアクセス権限
      properties:
        directoryAccessibilities:
          title: directoryAccessibilities
          type: array
          description: ディレクトリのアクセス権限
          items:
            $ref: '#/components/schemas/FileAccessibility'
        textResourceAccessibilities:
          title: textResourceAccessibilities
          type: array
          description: テキストリソースのアクセス権限
          items:
            $ref: '#/components/schemas/FileAccessibility'
        textAccessibilities:
          title: textAccessibilities
          type: array
          description: テキストデータのアクセス権限
          items:
            $ref: '#/components/schemas/FileAccessibility'
    Execution:
      title: Execution
      type: object
      description: 実行の設定
      properties:
        execTime:
          title: execTime
          type: number
          description: 実行時間(ms)
          example: 1000
        execMemory:
          title: execMemory
          type: number
          description: 実行メモリ(MB)
          example: 256
        resourceAccessibilities:
          title: resourceAccessibilities
          type: object
          description: リソースのアクセス権限
          $ref: '#/components/schemas/ResourceAccessibilities'
        entryPointShellScriptId:
          title: entryPointShellScriptId
          type: string
          description: エントリーポイントのシェルスクリプトのID
          format: uuid
          example: 68ffddc4-adc6-4f93-9ff2-d862ee6cce7a
    ExecutionsProcedure:
      title: ExecutionsProcedure
      type: object
      description: 実行の手順
      properties:
        resourceDeclaration:
          title: resourceDeclaration
          type: object
          description: 必要なリソースの宣言
          $ref: '#/components/schemas/ResourceDeclaration'
        executions:
          title: executions
          type: array
          description: 実行の設定
          items:
            $ref: '#/components/schemas/Execution'
    Judge:
      title: Judge
      type: object
      description: ジャッジの設定
      properties:
        testId:
          title: testId
          type: string
          description: テストのID
          format: uuid
          example: 68ffddc4-adc6-4f93-9ff2-d862ee6cce7a
        testCount:
          title: testCount
          type: number
          description: テストの数
          example: 3
        beforeTestProcedure:
          title: beforeTestProcedure
          type: object
          description: テスト前の手順
          $ref: '#/components/schemas/ExecutionsProcedure'
        beforeTestResourceDefinition:
          title: beforeTestResourceDefinition
          type: object
          description: テスト前のリソースの定義
          $ref: '#/components/schemas/ResourceDefinition'
        testProcedure:
          title: testProcedure
          type: object
          description: テストの手順
          $ref: '#/components/schemas/ExecutionsProcedure'
        testResourceDefinitions:
          title: testResourceDefinitions
          type: array
          description: テストのリソースの定義
          items:
            $ref: '#/components/schemas/ResourceDefinition'
        afterTestProcedure:
          title: afterTestProcedure
          type: object
          description: テスト後の手順
          $ref: '#/components/schemas/ExecutionsProcedure'
        afterTestResourceDefinition:
          title: afterTestResourceDefinition
          type: object
          description: テスト後のリソースの定義
          $ref: '#/components/schemas/ResourceDefinition'
