name: nix-buildcheck

on:
    push:
      branches: [ "develop" ]
    pull_request:
      branches: [ "develop" ]  


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix build ./exec-container/flake.nix
    - run: nix flake check ./exec-container/flake.nix