name: nix-buildcheck

on:
    push:
      branches: [ "develop" ]
    pull_request:
      branches: [ "develop" ]  


jobs:
 test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./exec-container
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install Nix
      run: curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install
    - name: nix-buildcheck
      run: nix build --extra-experimental-features 'nix-command flakes'